### ISSUE TITLE
不会配置，好东西不会用啊

### ISSUE THREAD

**Issue by kid9547** [fengqi/kodi-metadata-tmdb-cli#10]
哇塞，这个怎么用啊，完全弄不好。有没有稍微详细一点点的教程。

**Comment by fengqi** [comment]
你卡在哪步了，下载，配置参数，运行，应该不难啊

**Comment by kid9547** [comment]
> 

配置参数不太明白。
比如
1、“collector，影视文件扫描相关”，里面
        "skip_folders": [
            "tmdb",
            "@eaDir",
            "CERTIFICATE",
            "$RECYCLE.BIN",
            "RECYCLER",
            "SYSTEM VOLUME INFORMATION",
            "@EADIR",
            "ADV_OBJ",
            "PLEX VERSIONS",
            "Sample",
            "gallery",
            "metadata"
的作用是什么，我需不需要修改。
2、       "movies_nfo_mode": 2,
        "movies_dir": [
            "/volume1/down/movies"
        ],
        "shows_dir": [
            "/volume1/down/shows"
        ],
        "music_videos_dir": [
            "/volume1/down/videos"
中的文件夹地址，如果是电脑的里面我需要改成“D:\360极速浏览器X下载\kodi-tmdb-windows-amd64-v0.4.12”这样的类型吗
3、    "ffmpeg": {
        "max_worker": 4,
        "ffmpeg": "/usr/local/ffmpeg-5.0.1-amd64-static/ffmpeg",
        "ffprobe": "/usr/local/ffmpeg-5.0.1-amd64-static/ffprobe"
    }
这里面的文件路径我怎么才能找到呢
4、我用的是群晖nas，硬盘是挂载在电脑上的，我怕群晖不会弄，我才想在电脑上测试一下，现在遇到了这些问题。

**Comment by fengqi** [comment]
可以看下wiki，配置字段含义都有说明的

**Comment by fengqi** [comment]
老哥使用下来还有问题吗，我暂时关闭这个issue了，有需要再打开。
