### ISSUE TITLE
希望可以增加一项刮logo的。

### ISSUE THREAD

**Issue by hkthomas** [fengqi/kodi-metadata-tmdb-cli#11]
https://image.tmdb.org/t/p/original/********.png

从这个页面拉取，logo文件存在的话kodi播放界面左上角会显示，还是很美观的。本地文件名就是logo.png kodi :)

**Comment by fengqi** [comment]
我研究一下看看

**Comment by hkthomas** [comment]
感谢感谢 :)

**Comment by fengqi** [comment]
加上了

**Comment by hkthomas** [comment]
老哥，稳！ :)

**Comment by hkthomas** [comment]
老哥，使用下，发现有点小问题。

movies_nfo_mode为1时，movie不会刮logo，TV正常。

movies_nfo_mode为2时，movie与TV都能刮，但是刮得图片不对，都是些奇奇怪怪的图。

比如刮斗破苍穹，下载的logo是一张 Tencent live字样的图。。。。

**Comment by fengqi** [comment]
movies_nfo_mode 不影响下载logo的，刮不到logo的应该是本身没有相关信息，movie不像tv有有所谓的流媒体平台或者电视台，电影是获取的出品公司，我调试的时候，有些公司是不附带logo信息的。

斗破苍穹不知道你的是哪一部，https://www.themoviedb.org/search?query=%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9 我看了下应该是tencent video的logo或者湖南卫视

**Comment by hkthomas** [comment]
确实是这样，同一个资源，设置1的时候刮不了，设置2可以刮，我试了几次都是。

对对对，刮得是Tencent video那个图，我记错了不好意思。

那只能刮影视公司logo吗。

**Comment by hkthomas** [comment]
可以就用第一个79481那个动漫的试一下。

**Comment by fengqi** [comment]
刮削不了的文件信息提供下。

> 那只能刮影视公司logo吗。 
如果tv提供多个logo，当前是只下载第一个实际有图的，他们之间是评级，无法区分性质。同理movie也是，只能选择下或不下。

**Comment by hkthomas** [comment]
Spider-Man Across The Spider-Verse (2023) [1080p] [WEBRip] [5.1]

格式是这样的，设置1的时候除了logo，其他nfo图片等都刮到了，设置2，所有信息都能刮。

https://www.themoviedb.org/movie/569094-spider-man-across-the-spider-verse

**Comment by hkthomas** [comment]
> > 那只能刮影视公司logo吗。
> 
> 如果tv提供多个logo，当前是只下载第一个实际有图的，他们之间是平级，无法区分性质。同理movie也是，只能选择下或不下。

原来如此，理解了。

**Comment by fengqi** [comment]
> Spider-Man Across The Spider-Verse (2023) [1080p] [WEBRip] [5.1]
> 
> 格式是这样的，设置1的时候除了logo，其他nfo图片等都刮到了，设置2，所有信息都能刮。
> 
> https://www.themoviedb.org/movie/569094-spider-man-across-the-spider-verse

可以确认下是否是网络引起的图片下载失败，我测试没有问题的。

**Comment by hkthomas** [comment]
好的，回去我换个上网环境优选下TMDB的ip再试下，麻烦了。
.
https://image.tmdb.org/t/p/original/mhtjwFjpanI4p3fUL7XQFkcsVOV.png 确实只获取到了公司的logo.

**Comment by hkthomas** [comment]
老哥，我刚看了下官方的api试了下。

找到可以获取logo的方法了。

电影比如蜘蛛侠：569094

https://api.themoviedb.org/3/movie/569094/images?api_key=*

TV比如斗破苍穹：

https://api.themoviedb.org/3/tv/79481/images?api_key=*

这个页面内 PNG格式的都是电影的logo，jpg是剧照跟海报。

不知道有帮助吗。

**Comment by fengqi** [comment]
569094 拿到的信息里，第一个图片确实就是https://image.tmdb.org/t/p/w500/9y5lW86HnxKUZOFencYk3TIIRCM.png
完整信息是：

```
[
    {
      "id": 5,
      "logo_path": "/mhtjwFjpanI4p3fUL7XQFkcsVOV.png",
      "name": "Columbia Pictures",
      "origin_country": "US"
    },
    {
      "id": 2251,
      "logo_path": "/5ilV5mH3gxTEU7p5wjxptHvXkyr.png",
      "name": "Sony Pictures Animation",
      "origin_country": "US"
    },
    {
      "id": 77973,
      "logo_path": "/9y5lW86HnxKUZOFencYk3TIIRCM.png",
      "name": "Lord Miller",
      "origin_country": "US"
    },
    {
      "id": 84041,
      "logo_path": "/nw4kyc29QRpNtFbdsBHkRSFavvt.png",
      "name": "Pascal Pictures",
      "origin_country": "US"
    },
    {
      "id": 14439,
      "logo_path": null,
      "name": "Arad Productions",
      "origin_country": "US"
    }
  ],
```

**Comment by fengqi** [comment]
> 老哥，我刚看了下官方的api试了下。
> 
> 找到可以获取logo的方法了。
> 
> 电影比如蜘蛛侠：569094
> 
> https://api.themoviedb.org/3/movie/569094/images?api_key=*
> 
> TV比如斗破苍穹：
> 
> https://api.themoviedb.org/3/tv/79481/images?api_key=*
> 
> 这个页面内 PNG格式的都是电影的logo，jpg是剧照跟海报。
> 
> 不知道有帮助吗。

这个获取到的logo是影视本身的logo，不是流媒体或者电影公司的，你原本需要的就是这个吗

**Comment by fengqi** [comment]
> 是啊老哥，kodi只有放电影的时候左上角那电影名字下面才显示logo，显示公司logo没啥必要。。

那我搞错了，稍后修正下

**Comment by hkthomas** [comment]
辛苦老哥 :)

**Comment by fengqi** [comment]
可以再试试v0.4.15的版本

**Comment by hkthomas** [comment]
好的。

**Comment by fengqi** [comment]
涉及到缓存，需要删除 tmdb/tv.json 和 tmdb/movie.json 缓存文件。

**Comment by hkthomas** [comment]
谢谢老哥，测试了下，刮logo没问题了。
