### ISSUE TITLE
Windows版运行报错

### ISSUE THREAD

**Issue by gaodyoffice** [fengqi/kodi-metadata-tmdb-cli#14]
电脑：鸿基一体机
版本 Windows10
专业版版本号 22H2 
安装日期 10/11/2023 
操作系统内部版本 19045.4170

运行报错，代码如下：
D:\apps\kodi-tmdb-windows-amd64-v0.4.18>tmdb.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x13f182]

goroutine 1 [running]:
fengqi/kodi-metadata-tmdb-cli/utils.(*logger).FatalF(0xc000126000?, {0x36cf86?, 0x5d1?}, {0xc0000cbed8?, 0xc000123230?, 0xc000057ec8?})
        fengqi/kodi-metadata-tmdb-cli/utils/logger.go:105 +0x22
fengqi/kodi-metadata-tmdb-cli/config.LoadConfig({0x36934a?, 0x234d0721b88?})
        fengqi/kodi-metadata-tmdb-cli/config/config.go:18 +0xe8
main.main()
        fengqi/kodi-metadata-tmdb-cli/main.go:36 +0x39

**Comment by fengqi** [comment]
你检查下是不是配置文件有语法错误 https://www.bejson.com/

**Comment by gaodyoffice** [comment]
以下是配置，没发现哪有问题。我是参照example.config.json进行修改的，然后删除example.

{
    "log": {
        "mode": 1,
        "level": 2,
        "file": "/tmp/tmdb-collector.log"
    },
    "tmdb": {
        "api_host": "https://api.themoviedb.org",
        "image_host": "https://image.tmdb.org",
        "api_key": "7c3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "language": "zh-CN",
        "proxy": "socks5://127.0.0.1:3066",
        "rating": "US"
    },
    "collector": {
        "watcher": true,
        "cron_seconds": 3600,
        "skip_folders": [
            "tmdb",
            "@eaDir",
            "CERTIFICATE",
            "$RECYCLE.BIN",
            "RECYCLER",
            "SYSTEM VOLUME INFORMATION",
            "@EADIR",
            "ADV_OBJ",
            "PLEX VERSIONS",
            "Sample",
            "gallery",
            "metadata"
        ],
        "movies_nfo_mode": 1,
        "movies_dir": [
            "D:\apps\kodi-tmdb-windows-amd64-v0.4.18\movies"
        ],
        "shows_dir": [
            "D:\apps\kodi-tmdb-windows-amd64-v0.4.18\shows"
        ],
        "music_videos_dir": [
            "D:\apps\kodi-tmdb-windows-amd64-v0.4.18\videos"
        ]
    },
    "kodi": {
        "enable": false,
        "clean_library": false,
        "json_rpc": "http://192.168.1.123:8080/jsonrpc",
        "timeout": 1,
        "username": "kodi",
        "password": "123456"
    },
    "ffmpeg": {
        "max_worker": 4,
        "ffmpeg_path": "D:\apps\ffmpeg\ffmpeg\bin\ffmpeg.exe",
        "ffprobe_path": "D:\apps\ffmpeg\ffmpeg\bin\ffprobe.exe"
    }
}

**Comment by fengqi** [comment]
`"file": "/tmp/tmdb-collector.log"` 改成实际存在的位置吧

**Comment by gaodyoffice** [comment]
试过（"D:\apps\kodi-tmdb-windows-amd64-v0.4.18\tmdb-collector.log"），还是不行。还是原来的错误。

**Comment by gaodyoffice** [comment]
试过（"D:\apps\kodi-tmdb-windows-amd64-v0.4.18\tmdb-collector.log"），还是不行。还是原来的错误。

**Comment by fengqi** [comment]
把所有路径的斜杠改成 `D:\\apps\\kodi-tmdb-windows-amd64-v0.4.18\\tmdb-collector.log` 或者 `D:/apps/kodi-tmdb-windows-amd64-v0.4.18/tmdb-collector.log`

**Comment by gaodyoffice** [comment]
> 把所有路径的斜杠改成双斜杠或者反斜杠 `D:\\apps\\kodi-tmdb-windows-amd64-v0.4.18\\tmdb-collector.log` 或者 `D:/apps/kodi-tmdb-windows-amd64-v0.4.18/tmdb-collector.log`

可以了，谢谢。刚试了，很好用，就是得规范命名。
