### ISSUE TITLE
能否支持alist阿里网盘webdav挂载的刮削?

### ISSUE THREAD

**Issue by 123385918** [fengqi/kodi-metadata-tmdb-cli#4]
大佬好! 我在用alist挂载自己的阿里网盘, 然后电视端用kodi的webdav方式连接网盘实现的原画质播放 . kodi自带的刮削器会处理网盘内容(具体我也不是很懂) 导致网盘账号被风控, 所以只能选local那个刮削 , 需要我手动刮好, 在上传网盘相应文件夹 . 不知道大佬有无意愿实现下这种场景下的刮削支持?

**Comment by fengqi** [comment]
刮削后的NFO文件需要和视频文件在一起才能被识别，无法做到分离。
你这种需要刮削后上传阿里云，这个暂不想做，或者可以读写权限挂载到其他地方然后刮削。

**Comment by 123385918** [comment]
哦哦 上传阿里云的操作可以自己手动上传，大佬说的“读写权限挂载到其他地方”  是什么意思？

**Comment by fengqi** [comment]
> 哦哦 上传阿里云的操作可以自己手动上传，大佬说的“读写权限挂载到其他地方” 是什么意思？

比如挂载到一台电脑上，像刮削本地文件一样。

**Comment by 123385918** [comment]
> 

哦哦  alist支持这样挂载吗？现在您的代码支持这样刮削吗？

**Comment by fengqi** [comment]
你可以自己试下，我没用过alist，但是挂载后应该和本地文件一样，就可以刮削

**Comment by 123385918** [comment]
好的  我看网上应该能通过RaiDriver实现将阿里网盘挂载为只读 . 您代码能自定义下载的写入路径吗?
还有ffmpeg_path ffprobe_path 是必须的吗?

**Comment by fengqi** [comment]
> 好的 我看网上应该能通过RaiDriver实现将阿里网盘挂载为只读 . 您代码能自定义下载的写入路径吗? 还有ffmpeg_path ffprobe_path 是必须的吗?

只读不行，需要是可写入，不能自定义写入路径，需要和视频文件一起，

ffmpeg非必需，只是用于刮削普通视频文件生成封面的，比如MTV、自己拍的视频等，处理配置文件里的music_videos_dir的文件。

**Comment by 123385918** [comment]
好的, 谢谢您的指导, 我自己试一下再反馈[抱拳]

**Comment by 123385918** [comment]
找到了一个针对alist的刮削工具[onelist](https://github.com/msterzhang/onelist)
