### ISSUE TITLE
扫描的文件夹的时候出现了一个错误

### ISSUE THREAD

**Issue by lang07123** [fengqi/kodi-metadata-tmdb-cli#6]
![微信图片_20230404174825](https://user-images.githubusercontent.com/7733095/229754687-c924361b-8169-45b0-a448-0b817d7c7f5f.png)

我觉得这个问题因该是产生于我的目录结构, 但是又不知道应该如何修改,

**Comment by lang07123** [comment]
![图片](https://user-images.githubusercontent.com/7733095/229770475-ca2b61e6-3691-47f2-911b-1f05cb6822b0.png)
尝试修改后, 发现它拿到了, 第一季 第一集的名字

**Comment by fengqi** [comment]
可以尝试下最新构建的版本，解决此问题了。

**Comment by lang07123** [comment]
嗯。按照你说的方法解决了。。。
发现了一个新问题， 不过规整命名后解决了。。就是挺好玩的
所有的文件都识别成 S03.E04了并且只有最后一个文件生成了NFO

![Uploading 截屏2023-04-05 下午3.14.21.png…]()

**Comment by lang07123** [comment]
嗯。按照你说的方法解决了。。。
发现了一个新问题， 不过规整命名后解决了。。就是挺好玩的
所有的文件都识别成 S03.E04了并且只有最后一个文件生成了NFO
<img width="1223" alt="截屏2023-04-05 下午3 14 21" src="https://user-images.githubusercontent.com/7733095/230012407-7949a6c2-2c95-459d-8783-ca8b208d015e.png">

**Comment by fengqi** [comment]
这不应该啊，等我查查看

**Comment by lang07123** [comment]
<img width="1158" alt="截屏2023-04-05 下午4 27 36" src="https://user-images.githubusercontent.com/7733095/230026034-f777269c-d2df-44e9-998b-8e6c28588a22.png">

应该是文件分隔符导致的。。第一个有空格。第二个是-号分割

**Comment by fengqi** [comment]
又更新了一版，可以再尝试下🤣

PS: 出现这么多问题的原因是因为覆盖的特殊案例不够多，按照标准的命名方式就会比较精准，比如：
目录：救了一万次的你.Love.in.a.Loop.S01.2022，核心：中文或英文名字+S01+2022
文件：救了一万次的你.Love.in.a.Loop.S01E01.2022.mp4，核心：S01E02

**Comment by lang07123** [comment]
真心感谢。。帮大忙了。。。我就是心血来潮想给孩子搞个动画片看看。。。小米电视的会员一套下来1000+
原本以为这东西有什么难的， 结果从 kodi 搞到 nastools 搞到 jellyfin 搞到 jackett , 结果不是这里不合适就是哪里不合适。 最后还是 alist + 群晖 + kodi + 本地刮削。。本来想自己写一套刮削。一搜搜到你这个。

留个批量改名给后来人,rename 认为 - 是取参, 所以还是需要用shell
`for i in `ls *-S07-*`; do mv $i $(echo $i | sed 's/-S07-/.S07.E/'); done`

**Comment by fengqi** [comment]
> 真心感谢。。帮大忙了。。。我就是心血来潮想给孩子搞个动画片看看。。。小米电视的会员一套下来1000+ 原本以为这东西有什么难的， 结果从 kodi 搞到 nastools 搞到 jellyfin 搞到 jackett , 结果不是这里不合适就是哪里不合适。 最后还是 alist + 群晖 + kodi + 本地刮削。。本来想自己写一套刮削。一搜搜到你这个。
> 
> 留个批量改名给后来人,rename 认为 - 是取参, 所以还是需要用shell `` for i in `ls *-S07-*`; do mv $i $(echo $i | sed 's/-S07-/.S07.E/'); done ``

解决问题就好，我也是同样的原因所以自己写了刮削。。。
