### ISSUE TITLE
剧集的目录结构

### ISSUE THREAD

**Issue by Triwind** [fengqi/kodi-metadata-tmdb-cli#7]
感谢大佬的刮削工具给我的kodi观影带来更好的体验

不过好像目前的版本（v0.4.8）并不支持“剧/季/集”这样的目录结构
例如：电击少女 (2023)/Season 01/电击少女 (2023).S01E01.mp4
我在ubuntu 20.04上跑了一下
可以正确识别到剧集的名称和年份
并在“剧”的目录下生成nfo文件
但是会提示找不到“集”

> 2023/05/21 03:18:23 info search: 电击少女 or  2023 from tmdb
> 2023/05/21 03:18:23 info search tv: 电击少女 2023 result count: 1, use: &{95558 /pTeb4EsTy3hoVFpg9FnLIF3glZ5.jpg 90.387 /htZNH4PJwJCfiw6dbtpyXCuglXz.jpg 6.629 该剧改编自Naomi Alderman的同名小说，曾被前总统Barack Obama列为17年最爱书藉之一。《电击女孩》讲述全球各地的少女突然可以在手上发出电击，而 且她们还能用接触的方式为成年女子唤醒能力，于是一下子男女地位完全逆转。在首季中将包括伦敦﹑亚利桑那﹑尼日利亚及摩尔多瓦等地的角色。 2023-03-30 [US] [10765 9648 18] en 31 电击少女 The Power}
> 2023/05/21 03:18:23 info save tv detail to: /mnt/alist/aliyun/剧集/已完结/欧美/电击少女 (2023)/tmdb/tv.json
> 2023/05/21 03:18:23 info save tvshow.nfo to: /mnt/alist/aliyun/剧集/已完结/欧美/电击少女 (2023)/tvshow.nfo
> 2023/05/21 03:18:23 info download https://image.tmdb.org/t/p/original/pTeb4EsTy3hoVFpg9FnLIF3glZ5.jpg to /mnt/alist/aliyun/剧集/已完结/欧美/电击少女 (2023)/poster.jpg
> 2023/05/21 03:18:24 info download https://image.tmdb.org/t/p/original/htZNH4PJwJCfiw6dbtpyXCuglXz.jpg to /mnt/alist/aliyun/剧集/已完结/欧美/电击少女 (2023)/fanart.jpg
> 2023/05/21 03:18:24 info download https://image.tmdb.org/t/p/original/pTeb4EsTy3hoVFpg9FnLIF3glZ5.jpg to /mnt/alist/aliyun/剧集/已完结/欧美/电击少女 (2023)/season01-poster.jpg
> 2023/05/21 03:18:24 warning scan shows file empty: 电击少女 (2023)

上述的目录结构是kodi和jellyfin官方都推荐的
请参考：
[Naming video files/TV shows](https://kodi.wiki/view/Naming_video_files/TV_shows)
[Naming Scheme for Shows](https://jellyfin.org/docs/general/server/media/shows)

希望大佬能抽空看一下

**Comment by fengqi** [comment]
合集目前支持的方式是：
顶层目录名：name.s01-s02.year
子目录：name.s01.year，name.s02.year
子目录内文件：name.e01.mkv

嵌套式的目录结构一直有想做，不过我个人没这样组织的习惯，所以一直就搁置了，你可以先拉平目录或者按上面示例补上名字，我后面找时间适配下嵌套结构。

**Comment by Triwind** [comment]
感谢大佬的解决方案
我按你的示例改了改
现在的目录结构是：电击少女.s01-s02.2023/电击少女.s01.2023/电击少女 (2023).S01E01.mp4
可能是我的理解错误 还是不行
能识别到“电击少女 (2023).S01E01.mp4” 但获取nfo出错

> 2023/05/21 13:50:27 info find season: 1 episode: 1 电击少女 (2023).S01E01.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 2 电击少女 (2023).S01E02.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 3 电击少女 (2023).S01E03.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 4 电击少女 (2023).S01E04.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 5 电击少女 (2023).S01E05.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 6 电击少女 (2023).S01E06.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 7 电击少女 (2023).S01E07.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 8 电击少女 (2023).S01E08.mp4
> 2023/05/21 13:50:27 info find season: 1 episode: 9 电击少女 (2023).S01E09.mp4
> 2023/05/21 13:50:27 debug pass : fanart.jpg
> 2023/05/21 13:50:27 debug pass : poster.jpg
> 2023/05/21 13:50:27 debug pass : tmdb
> 2023/05/21 13:50:27 debug pass : tvshow.nfo
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-8
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 8 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-9
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 9 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-1
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 1 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-4
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 4 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-7
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 7 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-6
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 6 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-2
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 2 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-3
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 3 failed
> 2023/05/21 13:50:27 debug get tv episode detail from tmdb: 0 1-5
> 2023/05/21 13:50:27 warning get episode from tmdb: 0 season: 1 episode: 5 failed

改成：电击少女.s01.2023/电击少女 (2023).S01E01.mp4后，就完全没有问题
看来还是嵌套的问题，两层文件夹可以，三层不行

最后，还有个请求，不麻烦的话大佬看看能否加上：
在生成tmdb文件夹的同时 能否在里面加个.ignore文件
这样jellyfin在扫描库的时候就会忽略tmdb文件夹了
请参考：
[Excluding a directory](https://jellyfin.org/docs/general/server/media/excluding-directory/)

谢谢大佬

**Comment by fengqi** [comment]
tmdb文件会对jellyfin造成什么影响吗

**Comment by Triwind** [comment]
呃，草率了
如果按我之前的嵌套式的目录结构
jellyfin会把tmdb文件夹当成“季”文件夹
现在支持的这种会不会 没验证过
跟chatgpt要了个批量新建.ignore的命令

**Comment by fengqi** [comment]
安装我说的那种三层，不能识别的原因是一个bug，迟点会先修复掉

**Comment by fengqi** [comment]
合集的已经修复了，.ignore这种我后面研究下jellyfin的时候再看看，kodi下不会有这个问题，如果jellyfin也可以设置仅从nfo读取，按说也会正常的。

**Comment by Triwind** [comment]
经过验证，按你说的三层目录结构，v0.4.9版本确实能准确刮削到剧集信息了，给大佬点赞

> 2023/05/22 01:02:27 info save episode detail to: /mnt/alist/aliyun/剧集/已完结/欧美/电击少女.s01-s02.2023/电击少女.s01.2023/tmdb/s01e01.json
> 2023/05/22 01:02:27 info save episode nfo to: /mnt/alist/aliyun/剧集/已完结/欧美/电击少女.s01-s02.2023/电击少女.s01.2023/电击少女 (2023).S01E01.nfo
> 2023/05/22 01:02:27 info download https://image.tmdb.org/t/p/original/ofK3ckjVLLt376OG5Bwcu8N3xXg.jpg to /mnt/alist/aliyun/剧集/已完结/欧美/电击少女.s01-s02.2023/电击少女.s01.2023/电击少女 (2023).S01E01-thumb.jpg

至于嵌套式的，大佬有空就慢慢搞，这个issue我先关了

**Comment by fengqi** [comment]
👌
