### ISSUE TITLE
平台兼容性问题

### ISSUE THREAD

**Issue by nichuanfang** [fengqi/kodi-metadata-tmdb-cli#8]
大佬请问支持coreelec的linux系统吗 它这个好像不是amd64的

**Comment by fengqi** [comment]
我预编译的版本没有 linux-arm 的，加上也不算麻烦。

**Comment by nichuanfang** [comment]
我是电视盒子跑clouddrive2 想用这个 架构是 linux-aarch64 可以加一下吗 万分感谢!

**Comment by fengqi** [comment]
可以，晚点我加上

**Comment by nichuanfang** [comment]
栓q 大佬威武
